[[constraint]]
  branch = "master"
  name = "github.com/FernandoCagale/go-api-shared"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "github.com/Sirupsen/logrus"

[[constraint]]
  name = "github.com/joho/godotenv"